 CREATE DATABASE mydb;

 USE mydb;


 CREATE TABLE books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    naziv VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    zanr VARCHAR(255) NOT NULL
    ) ;

